dest_dir: "docs"
src_dir: "src"
app_name: "Onboarding"

environments:

  dev:
    debug: true
    privateKeyFile: "config/development/sbx_didkey_priv.txt"
    machineCredentialFile: "config/development/sbx_lear_credential_machine.txt"
    mydidkey: "did:key:zDnaeajw3FmMgsGJxWggMLbXFgr7yoeTBKBsPAdErbLpSFLZt"

    verifier:
      url: "https://verifier.dome-marketplace-sbx.org"
      token_endpoint: "https://verifier.dome-marketplace-sbx.org/oidc/token"
    issuer:
      credentialIssuancePath: "https://issuer.dome-marketplace-sbx.org/vci/v1/issuances"

    mail:
      onboard_team_email:
        - "jesus.ruiz@in2.es"
      issuer_team_email:
        - "hesus.ruiz@gmail.com"
      cc_list_email:
        - "jesus@alastria.io"
      smtp:
        enabled: true
        host: "smtp.ionos.de"
        port: 465
        tls: true
        username: "onboarding@dome-marketplace.eu"
        passwordFile: "config/development/smtppassword.txt"

